# Generated by Django 5.0.6 on 2024-06-15 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InvUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Supply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("barcodeID", models.CharField(max_length=255, unique=True)),
                ("quantityReplenished", models.IntegerField()),
                ("isLow", models.BooleanField(db_default=False)),
                (
                    "lastReplenished",
                    models.DateTimeField(
                        db_default=datetime.datetime(2024, 6, 15, 16, 57, 54, 99609)
                    ),
                ),
                ("whoReplenished", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("barcodeID", models.CharField(max_length=255, unique=True)),
                ("isCheckedOut", models.BooleanField()),
                ("timeCheckedOut", models.DateTimeField(blank=True, null=True)),
                ("userCheckedOut", models.CharField(blank=True, max_length=50)),
                ("location", models.CharField(max_length=255)),
            ],
        ),
    ]
