# Generated by Django 5.0.6 on 2024-06-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supply",
            name="lastReplenished",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
