# Generated by Django 5.0.6 on 2024-06-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0002_alter_supply_lastreplenished"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supply",
            name="quantityReplenished",
            field=models.CharField(max_length=255),
        ),
    ]
