# Generated by Django 5.0.6 on 2024-06-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_job_invuser_barcodeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='barcode_img',
            field=models.ImageField(default=None, upload_to='images/'),
            preserve_default=False,
        ),
    ]
