# Generated by Django 5.0.6 on 2024-06-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_job_barcode_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='barcode_img',
            field=models.ImageField(upload_to='jobs/images/'),
        ),
    ]
