# Generated by Django 5.0.6 on 2024-06-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_alter_job_barcode_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='barcode_img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='totalHours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='userScannedIn',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
