# Generated by Django 5.0.6 on 2024-06-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_alter_job_barcode_img_alter_job_totalhours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, unique=True)),
                ('user', models.CharField(max_length=255, unique=True)),
                ('subject', models.CharField(max_length=255, unique=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
