# Generated by Django 5.0.6 on 2024-06-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
