# Generated by Django 5.0.6 on 2024-06-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_alter_log_action_alter_log_subject_alter_log_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='subject',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
