# Generated by Django 5.0.6 on 2024-07-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_alter_log_action_alter_log_subject_alter_log_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kiln',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('barcodeID', models.CharField(max_length=255, unique=True)),
                ('isFilled', models.BooleanField()),
                ('timeFilled', models.DateTimeField(blank=True, null=True)),
                ('userFilled', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
